-- phase: expand
-- One `tools` database for all eight apps (plan T8, decision 3). Every key that could collide across
-- apps carries `app`. The runtime role creates no tables: this file is applied by migrations.
--
-- Not here on purpose (plan T8, decision 4):
--   guard_salt, guard_day, the minute/burst token buckets  -> Valkey (throttle state, worthless after a day)
--   the event outbox        -> migrations/0004_event_outbox.sql (openvibe-sdk createPgOutbox's table, as owner)
--   token_revocations       -> openvibe-sdk/auth createPgRevocationStore creates its own table at boot
--
-- `app` (the owning app, one row per app in the one database) has DEFAULT '' so scripts/migrate-to-postgres.js
-- can import a file that has no such column; the script sets the real value in the same pass and the runtime
-- always writes it explicitly. A default of '' is never a real owner.
-- analytics tables (analytics_events, analytics_hourly, analytics_daily, analytics_visitor_days,
-- analytics_day_salts and their indexes) are the analyticsSchema() DDL from
-- openvibe-shared/analytics/pg.js, copied verbatim into 0002_analytics.sql.

CREATE TABLE IF NOT EXISTS tool_jobs (
    id text PRIMARY KEY, app text NOT NULL DEFAULT '', type text NOT NULL, type_version integer NOT NULL DEFAULT 1,
    owner text NOT NULL, state text NOT NULL CHECK (state IN ('queued','running','succeeded','failed','cancelled')),
    progress double precision, progress_message text, input_json text NOT NULL DEFAULT '{}',
    files_json text NOT NULL DEFAULT '[]', result_json text, error_json text,
    retryable integer NOT NULL DEFAULT 0, idempotency_key text, request_hash text,
    attempts integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 1,
    cancel_requested integer NOT NULL DEFAULT 0, ttl_ms integer NOT NULL DEFAULT 3600000,
    created_at bigint NOT NULL, updated_at bigint NOT NULL, started_at bigint, finished_at bigint, expires_at bigint,
    env text NOT NULL DEFAULT 'production' CHECK (env IN ('production','sandbox')),
    retry_of text, retried_by text, ip_key text, tool text, project_id text, trace_id text);
CREATE UNIQUE INDEX IF NOT EXISTS tool_jobs_idem ON tool_jobs(app, owner, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS tool_jobs_state ON tool_jobs(app, state, id);
CREATE INDEX IF NOT EXISTS tool_jobs_expiry ON tool_jobs(app, expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS tool_jobs_owner ON tool_jobs(app, owner, state);
CREATE INDEX IF NOT EXISTS tool_jobs_ip ON tool_jobs(app, ip_key, state) WHERE ip_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS tool_job_events (
    seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id text NOT NULL,
    event text NOT NULL, data text NOT NULL, at bigint NOT NULL);
CREATE INDEX IF NOT EXISTS tool_job_events_job ON tool_job_events(job_id, seq);

CREATE TABLE IF NOT EXISTS tool_job_references (
    job_id text NOT NULL, ref text NOT NULL, created_at bigint NOT NULL, PRIMARY KEY (job_id, ref));

CREATE TABLE IF NOT EXISTS tool_job_usage (
    app text NOT NULL DEFAULT '', project_id text NOT NULL, env text NOT NULL, capability text NOT NULL,
    dimension text NOT NULL, window_start bigint NOT NULL, quantity integer NOT NULL DEFAULT 0,
    errors integer NOT NULL DEFAULT 0, error_codes text NOT NULL DEFAULT '{}', samples text NOT NULL DEFAULT '[]',
    revision integer NOT NULL DEFAULT 1, event_id text, emitted_at bigint,
    PRIMARY KEY (app, project_id, env, capability, dimension, window_start));
CREATE INDEX IF NOT EXISTS tool_job_usage_open ON tool_job_usage(app, emitted_at, window_start);

CREATE TABLE IF NOT EXISTS guard_abuse (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, app text NOT NULL DEFAULT '', at bigint NOT NULL,
    minute bigint NOT NULL, ip_hash text NOT NULL DEFAULT '', principal text NOT NULL DEFAULT '',
    tool text NOT NULL DEFAULT '', reason text NOT NULL, enforced integer NOT NULL, count integer NOT NULL DEFAULT 1);
CREATE UNIQUE INDEX IF NOT EXISTS guard_abuse_once ON guard_abuse(app, minute, ip_hash, principal, tool, reason, enforced);
CREATE INDEX IF NOT EXISTS guard_abuse_at ON guard_abuse(app, at);
