-- phase: expand
-- Request analytics on PostgreSQL (plan T8, decision 5). The DDL is analyticsSchema() from
-- openvibe-shared/analytics/pg.js, copied verbatim. One set of `service`-keyed tables serves the seven
-- tracking apps (img, audio, docs, text, yt, maps, food); service = app. The gateway runs no tracker.
-- analytics_rate_tracking is deliberately absent (the PG twin omits it; the SQLite one is emptied and
-- nothing reads it).

CREATE TABLE IF NOT EXISTS analytics_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service text NOT NULL,
    event_type text NOT NULL DEFAULT 'pageview',
    path text,
    method text DEFAULT 'GET',
    status_code integer,
    response_time_ms integer,
    user_id bigint,
    session_id text,
    ip text,
    country text,
    city text,
    user_agent text,
    referer text,
    is_bot integer DEFAULT 0,
    bot_type text,
    device_type text,
    browser text,
    os text,
    authenticated integer NOT NULL DEFAULT 0,
    created_at text NOT NULL
);
CREATE TABLE IF NOT EXISTS analytics_hourly (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service text NOT NULL, hour text NOT NULL,
    pageviews bigint DEFAULT 0, api_calls bigint DEFAULT 0, unique_visitors bigint DEFAULT 0, unique_users bigint DEFAULT 0,
    bot_hits bigint DEFAULT 0, avg_response_ms integer DEFAULT 0, error_count bigint DEFAULT 0, bandwidth_bytes bigint DEFAULT 0,
    top_paths text, top_referers text,
    UNIQUE (service, hour)
);
CREATE TABLE IF NOT EXISTS analytics_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service text NOT NULL, date text NOT NULL,
    pageviews bigint DEFAULT 0, api_calls bigint DEFAULT 0, unique_visitors bigint DEFAULT 0, unique_users bigint DEFAULT 0,
    new_users bigint DEFAULT 0, bot_hits bigint DEFAULT 0, avg_response_ms integer DEFAULT 0, error_count bigint DEFAULT 0,
    top_paths text, top_referers text, top_countries text, device_breakdown text, browser_breakdown text,
    UNIQUE (service, date)
);
CREATE TABLE IF NOT EXISTS analytics_visitor_days (
    service text NOT NULL, day text NOT NULL, hour text NOT NULL, vhash text NOT NULL,
    authenticated integer NOT NULL DEFAULT 0,
    PRIMARY KEY (service, hour, vhash)
);
CREATE TABLE IF NOT EXISTS analytics_day_salts (
    service text NOT NULL, day text NOT NULL, salt text NOT NULL,
    PRIMARY KEY (service, day)
);
CREATE INDEX IF NOT EXISTS idx_analytics_events_created ON analytics_events (created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_service ON analytics_events (service, created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_path ON analytics_events (service, path, created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_bot ON analytics_events (is_bot, created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_visitor_days_day ON analytics_visitor_days (service, day);
