#!/usr/bin/env bash
# Put a custom domain (e.g. youtubedownloadonline.com) in front of the Tools gateway.
#
#   sudo deploy/scripts/add-custom-domain.sh youtubedownloadonline.com [--dns-cloudflare]
#
# 1. Point the domain's A/AAAA records at this server first.
# 2. Run this script: it issues a certificate (HTTP-01 by default, or DNS-01 through the
#    Cloudflare credentials already on the host) and writes an nginx vhost that forwards
#    the domain, and www., to the gateway with the original Host header.
# 3. In openvibe.network/admin → Domains, attach the host to a tool (owner only). The gateway
#    picks it up within a minute; until then it answers 404 for the unknown host.
set -euo pipefail
DOMAIN="${1:?usage: add-custom-domain.sh <domain> [--dns-cloudflare]}"; MODE="${2:-}"
[[ "$DOMAIN" =~ ^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$ ]] || { echo "Not a valid hostname: $DOMAIN" >&2; exit 1; }
[[ "$DOMAIN" == *openvibe.* ]] && { echo "OpenVibe zones are already covered by their wildcard vhosts." >&2; exit 1; }
PORT="${GATEWAY_PORT:-4001}"; CONF="/etc/nginx/sites-available/custom-$DOMAIN.conf"; WEBROOT=/var/www/letsencrypt
mkdir -p "$WEBROOT"

if [[ ! -d "/etc/letsencrypt/live/$DOMAIN" ]]; then
  if [[ "$MODE" == "--dns-cloudflare" ]]; then
    certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare-openvibe.ini -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos
  else
    cat > "$CONF" <<NGINX
server { listen 80; listen [::]:80; server_name $DOMAIN www.$DOMAIN; location /.well-known/acme-challenge/ { root $WEBROOT; } location / { return 404; } }
NGINX
    ln -sf "$CONF" "/etc/nginx/sites-enabled/custom-$DOMAIN.conf"; nginx -t && systemctl reload nginx
    certbot certonly --webroot -w "$WEBROOT" -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos
  fi
fi

cat > "$CONF" <<NGINX
# Custom domain for an OpenVibe tool. Generated by add-custom-domain.sh; the gateway decides
# which tool this host is (openvibe.network/admin → Domains).
server { listen 80; listen [::]:80; server_name $DOMAIN www.$DOMAIN;
  location /.well-known/acme-challenge/ { root $WEBROOT; }
  location / { return 301 https://$DOMAIN\$request_uri; } }
server { listen 443 ssl http2; listen [::]:443 ssl http2; server_name www.$DOMAIN;
  ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
  return 301 https://$DOMAIN\$request_uri; }
server { listen 443 ssl http2; listen [::]:443 ssl http2; server_name $DOMAIN;
  ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
  client_max_body_size 512m;
  add_header Strict-Transport-Security "max-age=31536000" always;
  location / {
    proxy_pass http://127.0.0.1:$PORT; proxy_http_version 1.1;
    proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https;
    # Host-role headers come from the gateway only, never from a client.
    proxy_set_header X-OV-Tool ""; proxy_set_header X-OV-Host-Role ""; proxy_set_header X-OV-Canonical-Host ""; proxy_set_header X-OV-Short-Host "";
    proxy_buffering off; proxy_read_timeout 600s; proxy_send_timeout 600s;
  } }
NGINX
ln -sf "$CONF" "/etc/nginx/sites-enabled/custom-$DOMAIN.conf"
nginx -t && systemctl reload nginx
echo "Done. Now attach $DOMAIN to a tool in https://openvibe.network/admin (Domains tab)."
